import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import localFont from 'next/font/local';

// const inter = Inter({ subsets: ['latin'] });
const myFont = localFont({ src: '../../public/fonts/Manrope-VariableFont_wght.ttf', variable: '--font-manrope'})

export const metadata: Metadata = {
  title: 'Space Lane',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={myFont.variable + ' font-manrope'}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
