import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import localFont from 'next/font/local';
import { getLocale } from '../../i18n/server';
import { LocaleProvider } from '@/hooks/locale-provider';

// const inter = Inter({ subsets: ['latin'] });
const myFont = localFont({
  src: '../../public/fonts/Manrope-VariableFont_wght.ttf',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: 'Space Lane',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = getLocale();

  return (
    <html lang={locale}>
      <body className={myFont.variable + ' font-manrope'}>
        <LocaleProvider value={locale}>
          <Header />
          <main>{children}</main>
          <Footer />
        </LocaleProvider>
      </body>
    </html>
  );
}
